### PR TITLE
Adding encrypted config.ini for travis

### PR DESCRIPTION
**Pull request by paulwicking**
Required for integration tests in Travis CI.

### CODE REVIEW

**Comment by paulwicking** [comment]
According to Travis CI docs, this attempt is futile: "Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code."
https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

Makes sense, but we need a config.ini for setting up an integration test connection. This one has a general section that can be used to connect to the Atlassian SDK, and a section that connects to my pycontribs account.

@ssbarnea if you would give a thumbs up, I can (finally) create a new PR for the tests and first few things based off of the REST API :) (from https://github.com/wowsuchnamaste/confluence/commit/345cc62138620943553063ff856124925cc6939d)

**Comment by paulwicking** [comment]
After looking further into this matter, I've decided to close this pull request as it does not provide the expected solution.

I'll look into how we can establish integration tests that will work also during pull requests. So far, attempts at using the Atlassian SDK in Travis have turned out to be a poor solution. Due to its architecture, it requires a sleep() of 5-6 minutes, just for the SDK to initialize properly - and sometimes (depending on network load, it seems) even this is not sufficient.

**Comment by ssbarnea** [comment]
I could have told you the same: using Travis to run Jira via Atlassian SDK is not going to work due to resource restrains. For testing this we need a different CI system, maaybe even a private Jenkins instance.

This does not mean that Travis is bad or to be replaced, just that it needs to be used with an external Jira instance, like the cloud one we currently have. Also one of the big tricks is to assure that multiple tests can run in parallel, testing the same JIRA instance. Is possible but requires a lot of tuning.

**Comment by paulwicking** [comment]
I think Travis integrates nicely with the github repo, and it runs well-written (and mocked) unit tests just fine. A possible work-around is to run integration tests only for merges within the repository (i.e when merging from develop to master). This way, we can set up the encrypted config.ini (as was my intention) without completely compromising security. In any case, I would suggest we create a generic test user for the confluence instance (e.g. 'test-integration-user', or something similar), with access restrictions.

**Pull request closed without merging**
